-- 0011_better_auth.sql
--
-- Real authentication. Generated by `@better-auth/cli generate` for
-- better-auth 1.6.26, then made idempotent (this project has no migration
-- runner yet, so files get applied by hand and may be run twice) and extended
-- with the link to `profiles`.
--
-- ── Why `auth_*` and not Better Auth's defaults ──────────────────────────
-- Better Auth defaults to `user`, `session`, `account`, `verification`. This
-- database already has a `sessions` table holding therapy appointments — real
-- clinical records — which differs from `session` by one letter. The prefix
-- removes the ambiguity rather than trusting review to catch it.
--
-- ── Identity lives in `profiles`, not here ───────────────────────────────
-- 231 existing data calls key on `profiles.id` (uuid): `sessions.client_id`,
-- `tasks.therapist_id`, and so on. That stays the app's identity. `auth_user`
-- holds credentials only, and `profiles.auth_user_id` attaches a login to a
-- person. Two consequences that are the point of splitting them:
--   * an auth library upgrade can reshape auth_* without touching a clinical record
--   * a profile can exist before a login does (provider-invited clients), and a
--     login can be revoked without deleting the person's history

CREATE TABLE IF NOT EXISTS "auth_user" (
  "id"            text        NOT NULL PRIMARY KEY,
  "name"          text        NOT NULL,
  "email"         text        NOT NULL UNIQUE,
  "emailVerified" boolean     NOT NULL,
  "image"         text,
  "createdAt"     timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"     timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "auth_session" (
  "id"        text        NOT NULL PRIMARY KEY,
  "expiresAt" timestamptz NOT NULL,
  "token"     text        NOT NULL UNIQUE,
  "createdAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamptz NOT NULL,
  "ipAddress" text,
  "userAgent" text,
  "userId"    text        NOT NULL REFERENCES "auth_user" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "auth_account" (
  "id"                    text        NOT NULL PRIMARY KEY,
  "accountId"             text        NOT NULL,
  "providerId"            text        NOT NULL,
  "userId"                text        NOT NULL REFERENCES "auth_user" ("id") ON DELETE CASCADE,
  "accessToken"           text,
  "refreshToken"          text,
  "idToken"               text,
  "accessTokenExpiresAt"  timestamptz,
  "refreshTokenExpiresAt" timestamptz,
  "scope"                 text,
  -- Hashed by Better Auth (scrypt). Never a plaintext password.
  "password"              text,
  "createdAt"             timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"             timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS "auth_verification" (
  "id"         text        NOT NULL PRIMARY KEY,
  "identifier" text        NOT NULL,
  "value"      text        NOT NULL,
  "expiresAt"  timestamptz NOT NULL,
  "createdAt"  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "auth_session_userId_idx"          ON "auth_session" ("userId");
CREATE INDEX IF NOT EXISTS "auth_account_userId_idx"          ON "auth_account" ("userId");
CREATE INDEX IF NOT EXISTS "auth_verification_identifier_idx" ON "auth_verification" ("identifier");

-- The link. Nullable on purpose: the 6 seeded profiles have no login yet, and
-- a provider can invite a client (creating the profile) before that person ever
-- sets a password. UNIQUE so one login can never claim two people.
ALTER TABLE "profiles"
  ADD COLUMN IF NOT EXISTS "auth_user_id" text UNIQUE
  REFERENCES "auth_user" ("id") ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS "profiles_auth_user_id_idx" ON "profiles" ("auth_user_id");
